import localFont from "next/font/local";
import "./globals.css";
import CustomLink from "./components/CustomLink";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="border-b border-gray-400 p-4">
          <ul className="flex gap-5 text-xl">
          <li>
            <CustomLink path="/">Home</CustomLink>
          </li>
          <li>
            <CustomLink path="/about">About Us</CustomLink>
          </li>
          <li>
            <CustomLink path="/contact">Contact Us</CustomLink>
          </li>
          <li>
            <CustomLink prefetch={false} path="/dashboard/settings">Dashboard Settings</CustomLink>
          </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
